### ISSUE TITLE
I need to apply this! please

### ISSUE THREAD

**Issue by eincioch** [jsuarezruiz/dotNetMalaga2019#1]
Shell does not allow dynamic loading of menu options, according to a user profile, it must allow to show or hide options according to the login profile.

https://github.com/xamarin/Xamarin.Forms/issues/7230

NOTE: I have already sent it in as a suggestion, but there is no answer yet. Will there be another way?

**Comment by jsuarezruiz** [comment]
Is the correct way. You can see that the status has changed to "In progress". I close this one, follow up it in the Xamarin.Forms repo!.
